# Generated by Django 4.2 on 2023-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='No_of_guests',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Inventory',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
